title: "Chaostreff Flensburg e.V."
description: "Der Chaostreff Flensburg e.V. ist die Anlaufstelle für alle technikbegeisterten Nerds im Raum Flensburg und Umgebung. In unserem Raum, Space steht moderne Technik zum Kennenlernen und Ausprobieren bereit."
