title: "Chaos Computer Club Flensburg e.V."
description: "Der Chaos Computer Club Flensburg e.V. ist die Anlaufstelle für alle technikbegeisterten Nerds im Raum Flensburg und Umgebung. In unserem Raum, Space steht moderne Technik zum Kennenlernen und Ausprobieren bereit."
